INSERT INTO ride_pal.genres (id, name) VALUES (2, 'Afrikanische Musik');
INSERT INTO ride_pal.genres (id, name) VALUES (16, 'Asiatische Musik');
INSERT INTO ride_pal.genres (id, name) VALUES (75, 'Brasilianische Musik');
INSERT INTO ride_pal.genres (id, name) VALUES (81, 'Indische Musik');
INSERT INTO ride_pal.genres (id, name) VALUES (85, 'Alternative');
INSERT INTO ride_pal.genres (id, name) VALUES (95, 'Kids');
INSERT INTO ride_pal.genres (id, name) VALUES (98, 'Klassik');
INSERT INTO ride_pal.genres (id, name) VALUES (106, 'Electro');
INSERT INTO ride_pal.genres (id, name) VALUES (113, 'Dance');
INSERT INTO ride_pal.genres (id, name) VALUES (116, 'Rap/Hip Hop');
INSERT INTO ride_pal.genres (id, name) VALUES (129, 'Jazz');
INSERT INTO ride_pal.genres (id, name) VALUES (132, 'Pop');
INSERT INTO ride_pal.genres (id, name) VALUES (144, 'Reggae');
INSERT INTO ride_pal.genres (id, name) VALUES (152, 'Rock');
INSERT INTO ride_pal.genres (id, name) VALUES (153, 'Blues');
INSERT INTO ride_pal.genres (id, name) VALUES (165, 'R&B');
INSERT INTO ride_pal.genres (id, name) VALUES (169, 'Soul & Funk');
INSERT INTO ride_pal.genres (id, name) VALUES (173, 'Filme/Videospiele');
INSERT INTO ride_pal.genres (id, name) VALUES (197, 'Latin Musik');
INSERT INTO ride_pal.genres (id, name) VALUES (464, 'Heavy Metal');
INSERT INTO ride_pal.genres (id, name) VALUES (466, 'Folk');
